openapi: 3.0.3
info:
    title: Paid Leave API
    description: An API for managing Paid Family Leave
    version: '2022-03-11'

servers:
    - url: /v1
      description: Development server

paths:
    /status:
        get:
            tags:
                - Example Endpoints
            summary: Get the API status
            operationId: backend_engineer_interview.handlers.status
            responses:
                '200':
                    description: API is up and running
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Message!

    /employee/{id}:
        get:
            tags:
                - Test Endpoints
            summary: Fetch a single employee
            operationId: backend_engineer_interview.handlers.get_employee
            parameters:
                - name: id
                  in: path
                  schema:
                      type: integer
                  description: the employee id
                  required: true
            responses:
                '200':
                    description: Found the employee
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        example: 1
                                    first_name:
                                        type: string
                                        example: George
                                    last_name:
                                        type: string
                                        example: Harrison
                                    date_of_birth:
                                        type: string
                                        format: date
                                        example: '1943-02-25'
                '404':
                    description: No such employee
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
        patch:
            tags:
                - Test Endpoints
            summary: Fetch a single employee
            operationId: backend_engineer_interview.handlers.patch_employee
            parameters:
                - name: id
                  in: path
                  schema:
                      type: integer
                  description: the employee id
                  required: true
            responses:
                '204':
                    description: Successfully updated employee
                '404':
                    description: Employee does not exist
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                '400':
                    description: 'Bad request'
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                first_name:
                                    type: string
                                last_name:
                                    type: string
    /application:
        post:
            tags:
                - Test Endpoints
            summary: Create a new application
            operationId: backend_engineer_interview.handlers.post_application
            responses:
                '200':
                    description: Application created
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        example: 1
                                    employee_id:
                                        type: integer
                                        example: 1
                                    leave_start_date:
                                        type: string
                                        format: date
                                        example: '2022-03-11'
                                    leave_end_date:
                                        type: string
                                        format: date
                                        example: '2022-03-18'
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                employee_id:
                                    type: integer
                                leave_start_date:
                                    type: string
                                    format: date
                                leave_end_date:
                                    type: string
                                    format: date
        get:
            tags:
                - Test Endpoints
            summary: Search for applications
            operationId: backend_engineer_interview.handlers.search_application
            parameters:
                - name: search
                  in: query
                  schema:
                      type: string
                  description: the search term
                - name: limit
                  in: query
                  schema:
                      type: integer
                  description: the number of items to return
                - name: offset
                  in: query
                  schema:
                      type: integer
                  description: the number of items to skip
            responses:
                '200':
                    description: Found applications
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    applications:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                id:
                                                    type: integer
                                                    example: 1
                                                employee_id:
                                                    type: integer
                                                    example: 1
                                                leave_start_date:
                                                    type: string
                                                    format: date
                                                    example: '2022-03-11'
                                                leave_end_date:
                                                    type: string
                                                    format: date
                                                    example: '2022-03-18'
                                    count:
                                        type: integer
                                        example: 1
                                    limit:
                                        type: integer
                                        example: 10
                                    offset:
                                        type: integer
                                        example: 0
                                    next:
                                        type: string
                                        example: /v1/application?search=term&limit=10&offset=10
                                    prev:
                                        type: string
                                        example: /v1/application?search=term&limit=10&offset=0
                '400':
                    description: Bad request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
