"""Create applications

Revision ID: cafac01f835d
Revises: f6e4d4f5e121
Create Date: 2025-01-19 00:22:42.070865

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cafac01f835d"
down_revision = "f6e4d4f5e121"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("INSERT INTO application VALUES (1, '2021-01-01', '2021-02-01', 1)")
    op.execute("INSERT INTO application VALUES (2, '2021-02-01', '2021-03-01', 2)")
    op.execute("INSERT INTO application VALUES (3, '2021-03-01', '2021-04-01', 10)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
